### ISSUE TITLE
Wrapper for h

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/fd-velem#1]
Currently this is just a curryied wrapper for `virtual-dom/h`.
Should it do something else? Or do you (@hemanth) think it's okay like this?

**Comment by hemanth** [comment]
I think, we must have a bare minimal implementation of a virtual dom ourselves, just a wrapper to another lib is not that useful, wrapping a native DOM makes sense though.

**Comment by stoeffel** [comment]
> we must have a bare minimal implementation of a virtual dom ourselves

hmmm... is it really more useful too have a minimal self implementation, then using a proven lib inside our functions and just adding our sugar?
btw. `fd-isVdom` is using `virtual-dom` too atm.

**Comment by hemanth** [comment]
Yeah, did notice that.

**Comment by stoeffel** [comment]
I couldn't come up with a reason why we should implement our own virtual-dom implementation.
I still think we should use the awesome `virtual-dom`.

**Comment by hemanth** [comment]
:+1: Okies, let us keep this rolling and later on when the need arises, let's do out own implementation is a functional way.
